# Generated by Django 4.0.3 on 2022-06-14 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0004_alter_classofschool_classid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dateOfBirth',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 0, 0)),
        ),
    ]
